---
name: Load Parameters
description: Load parameters for the workflow

outputs:
  build_args:
    description: The build arguments
    value: ${{ steps.parse_args.outputs.build_args }}

runs:
  using: 'composite'
  steps:
    - name: Parse the build arguments
      id: parse_args
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs')
          const options = fs.readFileSync('./ci/build_options.txt').toString().trim().split('\n').join(' ')
          console.log(options)
          core.setOutput('build_args', options)
